future: true
permalink: /:title/
url: http://yjhjstz.github.io
name: yjhjstz
description: "Database Engineer | Open Source Contributor | Apache PPMC"
author: yjhjstz
twitter_username: yangjianghua
email: yjhjstz@gmail.com
weibo: yangjianghua
github: yjhjstz
paginate: 20
truncate: true
about: "Jianghua Yang"
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
